domain_id: 0
default_writer_qos:
  reliability: reliable
  history_kind: keep_last
  history_depth: 10
  durability: volatile
  liveliness: automatic
  deadline: infinite
default_reader_qos:
  reliability: best_effort
  history_kind: keep_last
  history_depth: 10
  durability: volatile
  liveliness: automatic
  deadline: infinite
